import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('api', {
  auth: {
    login:          (u: string, p: string) => ipcRenderer.invoke('auth:login', u, p),
    logout:         ()                     => ipcRenderer.invoke('auth:logout'),
    changePassword: (uid: number, cur: string, next: string) =>
                    ipcRenderer.invoke('auth:changePassword', uid, cur, next),
    requestReset:   (email: string) => ipcRenderer.invoke('auth:requestReset', email),
    verifyReset:    (otp: string, newPassword: string) => ipcRenderer.invoke('auth:verifyReset', otp, newPassword),
  },
  patients: {
    getAll:            (filters?: unknown)         => ipcRenderer.invoke('patients:getAll', filters),
    getById:           (id: number)                => ipcRenderer.invoke('patients:getById', id),
    search:            (query: string)             => ipcRenderer.invoke('patients:search', query),
    create:            (data: unknown)             => ipcRenderer.invoke('patients:create', data),
    update:            (id: number, data: unknown) => ipcRenderer.invoke('patients:update', id, data),
    softDelete:        (id: number, deletedBy?: number, reason?: string) => ipcRenderer.invoke('patients:softDelete', id, deletedBy, reason),
    getNextFileNumber: ()                          => ipcRenderer.invoke('patients:getNextFileNumber'),
  },
  appointments: {
    getAll:            (filters?: unknown)                          => ipcRenderer.invoke('appointments:getAll', filters),
    getByDate:         (date: string)                               => ipcRenderer.invoke('appointments:getByDate', date),
    getByDateRange:    (s: string, e: string)                       => ipcRenderer.invoke('appointments:getByDateRange', s, e),
    getById:           (id: number)                                 => ipcRenderer.invoke('appointments:getById', id),
    getTodayQueue:     ()                                           => ipcRenderer.invoke('appointments:getTodayQueue'),
    getAvailableSlots: (date: string, duration: number)             => ipcRenderer.invoke('appointments:getAvailableSlots', date, duration),
    create:            (data: unknown, userId?: number)             => ipcRenderer.invoke('appointments:create', data, userId),
    update:            (id: number, data: unknown, userId?: number) => ipcRenderer.invoke('appointments:update', id, data, userId),
    updateStatus:      (id: number, status: string, userId?: number)=> ipcRenderer.invoke('appointments:updateStatus', id, status, userId),
    cancel:            (id: number, reason: string, userId?: number)=> ipcRenderer.invoke('appointments:cancel', id, reason, userId),
  },
  medicalRecords: {
    getByPatient:    (patientId: number)                      => ipcRenderer.invoke('medicalRecords:getByPatient', patientId),
    getById:         (id: number)                             => ipcRenderer.invoke('medicalRecords:getById', id),
    getByAppointment:(apptId: number)                         => ipcRenderer.invoke('medicalRecords:getByAppointment', apptId),
    create:          (data: unknown, userId?: number)         => ipcRenderer.invoke('medicalRecords:create', data, userId),
    update:          (id: number, data: unknown)              => ipcRenderer.invoke('medicalRecords:update', id, data),
    delete:          (id: number)                             => ipcRenderer.invoke('medicalRecords:delete', id),
  },
  services: {
    getAll:       (includeInactive?: boolean)  => ipcRenderer.invoke('services:getAll', includeInactive),
    create:       (data: unknown)              => ipcRenderer.invoke('services:create', data),
    update:       (id: number, data: unknown)  => ipcRenderer.invoke('services:update', id, data),
    toggleActive: (id: number)                 => ipcRenderer.invoke('services:toggleActive', id),
  },
  invoices: {
    getAll:         (filters?: unknown)                          => ipcRenderer.invoke('invoices:getAll', filters),
    getById:        (id: number)                                 => ipcRenderer.invoke('invoices:getById', id),
    getByPatient:   (patientId: number)                          => ipcRenderer.invoke('invoices:getByPatient', patientId),
    create:         (data: unknown, userId?: number)             => ipcRenderer.invoke('invoices:create', data, userId),
    update:         (id: number, data: unknown, userId?: number) => ipcRenderer.invoke('invoices:update', id, data, userId),
    cancel:         (id: number, userId?: number)                => ipcRenderer.invoke('invoices:cancel', id, userId),
    getOutstanding: ()                                           => ipcRenderer.invoke('invoices:getOutstanding'),
    getNextNumber:  ()                                           => ipcRenderer.invoke('invoices:getNextNumber'),
  },
  payments: {
    getByInvoice: (invoiceId: number)               => ipcRenderer.invoke('payments:getByInvoice', invoiceId),
    create:       (data: unknown, userId?: number)  => ipcRenderer.invoke('payments:create', data, userId),
    delete:       (id: number, userId?: number)     => ipcRenderer.invoke('payments:delete', id, userId),
  },
  reports: {
    getDashboardStats:   (date: string)               => ipcRenderer.invoke('reports:getDashboardStats', date),
    getFinancialSummary: (start: string, end: string) => ipcRenderer.invoke('reports:getFinancialSummary', start, end),
    getAppointmentStats: (start: string, end: string) => ipcRenderer.invoke('reports:getAppointmentStats', start, end),
    getEndOfDay:         (date: string)               => ipcRenderer.invoke('reports:getEndOfDay', date),
  },
  settings: {
    getAll:     ()                                               => ipcRenderer.invoke('settings:getAll'),
    get:        (key: string)                                    => ipcRenderer.invoke('settings:get', key),
    set:        (key: string, value: string, userId?: number)    => ipcRenderer.invoke('settings:set', key, value, userId),
    setMany:    (data: Record<string, string>, userId?: number)  => ipcRenderer.invoke('settings:setMany', data, userId),
    getUsers:   ()                                               => ipcRenderer.invoke('settings:getUsers'),
    createUser: (data: unknown, userId?: number)                 => ipcRenderer.invoke('settings:createUser', data, userId),
    updateUser: (id: number, data: unknown, userId?: number)     => ipcRenderer.invoke('settings:updateUser', id, data, userId),
  },
  backup: {
    createNow:          ()               => ipcRenderer.invoke('backup:createNow'),
    restore:            (path: string)   => ipcRenderer.invoke('backup:restore', path),
    chooseBackupPath:   ()               => ipcRenderer.invoke('backup:chooseBackupPath'),
    chooseRestorePath:  ()               => ipcRenderer.invoke('backup:chooseRestorePath'),
    getLastBackupTime:  ()               => ipcRenderer.invoke('backup:getLastBackupTime'),
    toUSB:              ()               => ipcRenderer.invoke('backup:toUSB'),
    toDrive:            ()               => ipcRenderer.invoke('backup:toDrive'),
  },
  recycle: {
    getDeletedPatients: ()             => ipcRenderer.invoke('recycle:getDeletedPatients'),
    restorePatient:     (id: number)   => ipcRenderer.invoke('recycle:restorePatient', id),
    permanentDelete:    (id: number)   => ipcRenderer.invoke('recycle:permanentDelete', id),
  },
  system: {
    openFile:         (path: string)                       => ipcRenderer.invoke('system:openFile', path),
    saveFileDialog:   (name: string, filters: unknown[])   => ipcRenderer.invoke('system:saveFileDialog', name, filters),
    openFolderDialog: ()                                   => ipcRenderer.invoke('system:openFolderDialog'),
    getAppVersion:    ()                                   => ipcRenderer.invoke('system:getAppVersion'),
    openURL:          (url: string)                        => ipcRenderer.invoke('system:openURL', url),
    toggleFullscreen: ()                                   => ipcRenderer.invoke('system:toggleFullscreen'),
    isFullscreen:     ()                                   => ipcRenderer.invoke('system:isFullscreen'),
  },
  license: {
    getStatus:    ()              => ipcRenderer.invoke('license:getStatus'),
    activate:     (key: string)  => ipcRenderer.invoke('license:activate', key),
    getMachineId: ()              => ipcRenderer.invoke('license:getMachineId'),
  },
  audit: {
    getLog: (filters?: unknown) => ipcRenderer.invoke('audit:getLog', filters),
  },
})
